import {games,checkBatch} from './checker.js';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};
let database={draws:[]},limit=30;
for(const [id,name] of Object.entries(games)){$('#game').add(new Option(name,id))}$('#game').value='loto7';
function tabs(id){for(const kind of ['single','batch']){$(`#${kind}`).hidden=kind!==id;$(`#${kind}-tab`).setAttribute('aria-selected',String(kind===id))}}
for(const kind of ['single','batch']){$(`#${kind}-tab`).onclick=()=>tabs(kind);$(`#${kind}-tab`).onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=kind==='single'?'batch':'single';tabs(next);$(`#${next}-tab`).focus()}}}
function fields(){const g=$('#game').value,n=g.startsWith('numbers'),regional=!['loto6','loto7','miniloto','bingo5','numbers3','numbers4'].includes(g);$('#mode-label').hidden=!n;$('#group-label').hidden=!regional;$('#group').required=regional;$('#mode option[value=mini]').disabled=g!=='numbers3';if(g!=='numbers3'&&$('#mode').value==='mini')$('#mode').value='straight';$('#pick').placeholder=n?'例如 007':regional?'例如 178080':'例如 08 10 20 22 23 27 37';$('#pick-hint').textContent=n?'保留前导零；Numbers3 mini 输入末两位。':regional?'输入 6 位号码和彩票上的組。':g==='bingo5'?'按从左到右、从上到下输入 8 个号码，跳过 FREE；各格范围为 1–5、6–10…36–40。':'号码之间用空格或逗号分隔；不输入 bonus。';limit=30;history()}
function sourceLink(url){try{const u=new URL(url);if(u.protocol==='https:'&&u.hostname==='www.mizuhobank.co.jp'){const a=el('a','官方开奖 ↗');a.href=u.href;a.target='_blank';a.rel='noopener';return a}}catch{}return el('span','官方来源不可用')}
function history(){const g=$('#game').value,m=$('#month').value;const rows=database.draws.filter(d=>d.game===g&&(!m||d.date?.startsWith(m))).sort((a,b)=>b.draw-a.draw);$('#count').textContent=`${rows.length} 期 · ${games[g]}`;$('#draw-options').replaceChildren(...rows.map(d=>new Option(`${d.date} · 第${d.draw}回`,String(d.draw))));$('#history').replaceChildren();for(const d of rows.slice(0,limit)){const tr=el('tr'),name=el('td',`第${d.draw}回`);name.append(el('small',games[d.game]));tr.append(name,el('td',d.date||'日期未记录'));const ns=el('td');if(d.numbers){for(const n of d.numbers)ns.append(el('span',String(n).padStart(2,'0'),'ball'));for(const n of d.bonus||[])ns.append(el('span',String(n).padStart(2,'0'),'ball bonus'))}else if(d.number)ns.textContent=d.number;else ns.append(sourceLink(d.source));const action=el('td'),b=el('button','选此期','use');b.type='button';b.onclick=()=>{$('#draw').value=String(d.draw);tabs('single');$('#pick').focus();$('#single').scrollIntoView({behavior:'smooth',block:'center'})};action.append(b);tr.append(ns,action);$('#history').append(tr)}if(!rows.length){const tr=el('tr'),td=el('td','暂无符合条件的已同步记录。可以输入期号，缺失数据将返回 UNKNOWN。');td.colSpan=4;tr.append(td);$('#history').append(tr)}$('#more').hidden=rows.length<=limit;const dates=rows.map(d=>d.date).filter(Boolean).sort();$('#coverage').textContent=dates.length?`当前筛选实际覆盖 ${dates[0]} — ${dates.at(-1)}，共 ${rows.length} 期；区间内可能缺期，请以清单为准。黄色号码为 bonus。`:'这个类别／月份尚无可核对数据。'}
$('#more').onclick=()=>{limit+=50;history()};$('#game').onchange=fields;$('#month').onchange=()=>{limit=30;history()};
const format=v=>v==null?'金额未公布':`¥ ${v.toLocaleString('ja-JP')}`;
function render(results){$('#results').replaceChildren();for(const r of results){const card=el('article',undefined,'result');card.append(el('h3',`${r.index+1}. ${games[r.game]||'彩票'}${r.draw?' · 第'+r.draw+'回':''}`),el('span',({WIN:'WIN · 号码符合奖项',LOSE:'LOSE · 未中奖',UNKNOWN:'UNKNOWN · 无法判定'})[r.status],`badge ${r.status}`));if(r.error)card.append(el('p',r.error));else{card.append(el('p',`我的号码：${typeof r.ticket==='object'&&!Array.isArray(r.ticket)?`${r.ticket.group}組 ${r.ticket.number}`:Array.isArray(r.ticket)?r.ticket.map(x=>String(x).padStart(2,'0')).join(' · '):r.ticket}${r.mode?' / '+r.mode:''}`));if(r.matches){for(const m of r.matches)card.append(el('p',`${m.grade} · ${format(m.yen_per_ticket)} / 张`));if(r.matches.length)card.append(el('p','奖项分别列出，不推定特殊期次的奖项叠加方式。'))}else{card.append(el('div',format(r.total_yen),'amount'));card.append(el('p',`${r.grade||'未符合奖项'} · ${r.copies} 注${r.lines!==undefined?' · '+r.lines+' 条 BINGO 连线':''}`))}if(r.note)card.append(el('p',r.note));card.append(sourceLink(r.source));const d=database.draws.find(d=>d.game===r.game&&d.draw===r.draw);card.append(el('p',`开奖 ${r.date||'—'} · 此期数据读取 ${d?.fetched_at?new Date(d.fetched_at).toLocaleString():'历史快照，读取时间未记录'}`,'meta'))}$('#results').append(card)}$('#results').scrollIntoView({behavior:'smooth',block:'nearest'})}
async function refreshData(){const response=await fetch(`./data/results.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const latest=await response.json();if(!Array.isArray(latest.draws))throw Error('数据格式异常');database=latest;return latest}
$('#single').onsubmit=async e=>{e.preventDefault();try{await refreshData();const g=$('#game').value;const ticket={game:g,draw:$('#draw').value,copies:Number($('#copies').value)};if($('#month').value)ticket.month=$('#month').value;if(g.startsWith('numbers'))Object.assign(ticket,{number:$('#pick').value,mode:$('#mode').value});else if(['loto6','loto7','miniloto','bingo5'].includes(g))ticket.numbers=$('#pick').value;else Object.assign(ticket,{number:$('#pick').value,group:$('#group').value});render(checkBatch([ticket],database.draws));history()}catch(err){render([{index:0,status:'UNKNOWN',error:`开奖数据刷新失败（${err.message}）` }])}};
$('#batch').onsubmit=async e=>{e.preventDefault();try{const tickets=JSON.parse($('#batch-json').value);if(!Array.isArray(tickets)||!tickets.length||tickets.length>1000)throw Error('请输入包含 1–1000 张彩票的 JSON array');await refreshData();render(checkBatch(tickets,database.draws));history()}catch(err){render([{index:0,status:'UNKNOWN',error:err.message}])}};
$('#example').onclick=()=>{$('#batch-json').value=JSON.stringify([{game:'loto7',draw:'0691',numbers:[8,10,20,22,23,27,37]},{game:'numbers3',draw:'7072',number:'229',mode:'set'},{game:'kct',draw:'2708',month:'2026-03',group:'05',number:'123456'}],null,2)};
fields();
try{await refreshData();const when=database.last_success?new Date(database.last_success).toLocaleString():'尚未完成联网同步';$('#sync-state').textContent=`共收录 ${database.draws.length} 期。最近成功读取：${when}。${database.sync_status==='ok'?'最近同步成功。':database.sync_status==='partial'?'最近同步部分失败，保留此前有效数据。':'最近同步未成功，保留此前有效数据。'}${database.seed_note?' '+database.seed_note:''}`;history()}catch(e){$('#sync-state').textContent=`开奖数据加载失败（${e.message}）。当前无法查奖，结果将显示 UNKNOWN。`;history()}
